push = false
publish = true
allow-branch = ["master"]
dependent-version = "upgrade"
pre-release-commit-message = "release: {{crate_name}} version {{version}}"

[[pre-release-replacements]]
file = "src/lib.rs"
search = "\\[doc\\(html_root_url = .*\\)\\]"
replace = "[doc(html_root_url = \"https://docs.rs/{{crate_name}}/{{version}}\")]"
exactly = 1
