push = false
publish = false
allow-branch = ["master"]
dev-version-ext = "dev"
pre-release-commit-message = "release: {{crate_name}} version {{version}}"
post-release-commit-message = "chore: start work on {{crate_name}} version {{next_version}}"

[[pre-release-replacements]]
file = "src/lib.rs"
search = "\\[doc\\(html_root_url = .*\\)\\]"
replace = "[doc(html_root_url = \"https://docs.rs/{{crate_name}}/{{version}}\")]"
exactly = 1
