[[pre-release-replacements]]
file = "src/lib.rs"
search = "\\[doc\\(html_root_url = .*\\)\\]"
replace = "[doc(html_root_url = \"https://docs.rs/{{crate_name}}/{{version}}\")]"
exactly = 1

[[pre-release-replacements]]
file = "../README.md"
search = "serde_dhall = \".*\""
replace = "{{crate_name}} = \"{{version}}\""
exactly = 1

[[pre-release-replacements]]
file = "../README.md"
search = "#### \\[Unreleased\\]"
replace = "#### [Unreleased]\n\n#### [{{version}}] - {{date}}"
exactly = 1

[[pre-release-replacements]]
file = "../README.md"
search = "\\[Unreleased\\]:"
replace = "[{{version}}]:"
exactly = 1

[[pre-release-replacements]]
file = "../README.md"
search = "\\.\\.\\.HEAD"
replace = "...{{tag_name}}"
exactly = 1

[[pre-release-replacements]]
file = "../README.md"
search = "<!-- next-url -->"
replace = "<!-- next-url -->\n[Unreleased]: https://github.com/Nadrieril/dhall-rust/compare/{{tag_name}}...HEAD"
exactly = 1
